start_directory: /home/archbtw/dev/projects/snooker_score_board
session_name: snooker_score_board
windows:
  - window_name: editor
    panes:
      - shell_command:
          - nvim
  - window_name: service
    panes:
      - shell_command:
          - five-server
